### ISSUE TITLE
Card Component

### ISSUE THREAD

**Issue by Gauravsharma-20** [PEC-CSS/Stock-Watchlist#3]
![WhatsApp Image 2022-01-06 at 3 03 38 PM](https://user-images.githubusercontent.com/51043392/148430397-621a0a21-f848-4556-978a-584049d202a5.jpeg)

**Comment by ken1000minus7** [comment]
![image](https://user-images.githubusercontent.com/78747188/148654112-77542211-bd2f-4ccf-9d92-f54fb8cb2e8f.png)
Card component completed but no functionality added as of now, let me know if anything need to be modified or added (also i committed directly by mistake instead of making a pull req :(   )

**Comment by Gauravsharma-20** [comment]
Great work. Try rendering the static data collection.
